language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: deploy to production
    script: npm run build
    deploy:
      provider: heroku
      cleanup: true
      api_key: "$HEROKU_API_KEY"
      strategy: git
      app: reactjs-ci
      on:
        branch: master
notifications:
  slack:
    secure: HPWVJDdl6gEA4RnTm4LgGOgq2AThBI+rWDn4i2kD99L5vJTxtqhMIRutUs4QlH6x15zhu0LUqSFHLZSqxU6QdG/RSj86Nj1RGvElf527LbqQRoxDIhGPARj5Hueh7KqaCGX9KCrQiVTDUqlNsbOUbz97B6A74a47kM2QU8St+5Cnm3wi7Hi9IlqxX/dRme1fWdtSRKxn7eq59aL1hhndqyo/S+cVf8D8bhyNgAm8wxxYvuN0ghQq468Xr7UYSbfMSw9M1MzrsTcYJkxvcKfe6lP2MzHKPPKPoGqU0uxQNnBEGvSi85/KtqQmhU8QqTnVZarF018NoO4zskynPLaE6SdcKccbE/K12QG70KNMn7JdqG684AnbsVcBAl7BcWSN7kudFX/tsr1KjnZ++37DJk2UOIeuNjWhKsaCxXhzwYgMFu5m73v5MQee0fowxdW0HgIVK+DSz1M1V1RDhlkNVAKFqQhxuqNRErUKeFd2oemCrptZKanfn2rM7VR/V2lv4NiTOxxRKv1tADTqf3xsALR0sxXYBBs0tfICgLJGM4flPcwhylTJQTvhy6iEIk5K84deRVAxuJfMPAiu+kg4dQr/My4pB6pMPbwn4xeQDlE4GjYu5mpRlokVkANC5S5/ZkauLMT3+7beTUJVHZXMw6j+4T7rOATU/gNGav4oCLE=
    rooms:
      secure: E4v/fsuuxYDANmltld7jc4dhTE5rZCqRDin8no7QgoDptM24PaxSI6vuTjl3DfAt+qcM4qVc6aJE4vHTSZgYImpCP/lDAy9e5XKBDP/kcRX+gSSG/zNB2mYhjrBubB8+C5AmtHqZ2JJyN9ALdSJOYSDX8kjCdpVmOkB+cMNrqX8dc8rnBp9nJ4Nf/VlVaxt7HfwY6S9M9hA/086ys+Qp6YomlcoTJ7uop+sWGkonYXdNovV6D4wZf1bev8hVBTE3NyFvp5Szpl0CAtQL2haR2gK3dEfHQqwU4/6fjKpo07+fblBemIkLr9Xnd2As0xUmPyV5l3ZCh0yph2xBfrYmSMg0Wg1S4eHH1DpSPrNIc2JZawvRYzT7tuIKFSKjYx5ryaN7t4fDlIUchRb616Yv1jAWQ/dEllIFm1bR51iX5r0Yatt6FmFKpZpF+8kh9/c1ZFxiAaj3gKWijN1tns3lDRFkAUpNAvO7Gn9dI6fdG6N/5nPwBxI/Phn2pWEniYN/cvGuwbOFnC2pG8LCXc7GXF0QvSv2dht7uUeAb5bKd7y46ltAU7poHHUM0C+ZQgBad+08JBXwpMumc96UI75Nzwq4OjWBjLaC6F8EgiAPZJhuCfgrDQ7KX+8US/MRIoBFcnsR0ohXCbazPNdFvW4Bife4yDoj1vBGedI9JU4TBtk=
