language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
jobs:
  include:
  # - stage: unit tests
  #   script: npm test
  - stage: deploy to production
    script: npm run build
    deploy:
      provider: heroku
      cleanup: true
      api_key: "$HEROKU_API_KEY"
      strategy: git
      app: reactjs-ci
      on:
        branch: master
notifications:
  slack:
    secure: R0kJhsvVT1Jr3//lSevE2Gi0X91hPAtJ31tA4aWP3p0jCsKfc83z/eBQkRSmRwARAONAp57rswBWW9wzFRaXmnKK26vcprqCi/xk9NKmuJsRVVNQ0a8FwXVURmVDHupwrqNBCFu+QCoRz8rv4OU9A68xkFSNjhOurSz7E7EFk8DRhIM278hV0BPxhlRjMhGT3t9RI1vKvM8NESxs5ogi4gOp+Z1KdZtxXvfi//7NQmLJyHlQVBAxQPxqHrzRzycF2MFLxzjIJlp2XBBotDGEIXDWBjZYWLNKmH/30HfqqQt2j/vJ4PFATOPc3Y1N3FM6S+vedo0hvdnsxmRaaNQsTO2CvtlT+dN1Sg5uY7D9/JEZ9Z4iSxgenIzHpnkJBW/GtMnVD+fhn24VmJZxwKWKY82g8q4NM0e+sEc3O4EIcpoN/N8EutSrRVtp3v2ddJCUqFZXvvdG3gaP6lrANoKjuvriSPQZjR4mOjZtsqFddL/q4wdY9mtF/lwYWD49wyfQ2PqDE9sVL1O0To4P57eC1FABwc24I+tjE2KQ0Ev/ugXvMFhgE6BWA1H66GPOzXPcqQBSTOPTvV5Xzalvga6ivX/zz0POMZlO41d6oRLfSoGCl9FfSeZh8jjdhRWW2Kr7Lh+uFN4qs9IZxdHSKV99osxfJlyfk1wTXgJtJgzi76o=
