language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: code inspection
    addons:
      sonarcloud:
        organization: maurorojascabj
    script:
    - sonar-scanner
  - stage: deploy to production
    script: npm run build
    deploy:
      provider: heroku
      cleanup: true
      api_key: "$HEROKU_API_KEY"
      strategy: git
      app: reactjs-ci
      on:
        branch: master
notifications:
  slack: ingenieriasof-97b7969:leLR2neDDHJhQqfmGqu8D1nF
env:
  global:
    secure: D1WfYxAkSFM3dpLpJPVpSfUJq4vRd+IlfBmGdWMgEqrpFfQIamuq5RGMPPBmhcIGWOBAB6RoGq1TQ1y51Rpkay1tXyVKFVD+2CahjHUMoGsdsWJOa21dYQCOVmh/Piw2RdWrAgMhAE05C+A+w+ntYsE3RbJG8kk/TtmdrgX8tsBhVaoX8IVV8wUlsR4hhWSGvXVkLk83yAljhQQmiRm4Jd5aSnNa6mlucATNz+2p0k+av7T03m8SeDimuaU/jUOmDjVyUqKQQADfh6f3p7yUlbJ0myloYDO+E6XjyDDB8PmZ4iSWQy6BBR5cpNJz8E89bxOLE/iMe6LNbY75KrE59o3Le1ayPllVCq8cigU0rC9kZf+xgMYhLSJEeRTwlbgPgjg0hOrmX0ZJfRWBrve+UcfVFAWl0uBRLVW6aQ+4negGnxABjgEF4OLV1Ol94KC7lxBsK3jmLrXi7tpK7mGCRcuea9ZCKJgyoKHpfixaRoUDO7MZvvm/5k6A45YupmPsGnvM3z8ZyCcOQPxAUDGx7LEH6H5SFHJgSBCAtgf/Z6u2e09gz/J/gZmWK7mhJ0oPLo9pORqa8KzLduzsUL+bukycmN+01N1ZzlXxfIb5zvXY6o+4Q4/IyOMMAiwQgwsNlomXp+rAgbnhLV4slum4wyt7g4SF744iUOHcn/ROs30=
