language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: code inspection
    addons:
      sonarcloud:
        organization: maurorojascabj
        token:
          secure: "CogOS5qju3PjabGgomffvtL1+b3XlUK9+7Qr/XfIcIllziLtMrK04iPc/zAcFAwz16ce7EShvWm/7KASVaZMIAhhSTJKAC9Tzvz8vDRE0w4kiwchSI5xjUKqVa9sd930XQ1OB47p4GhUNcyaSYhRDc/vw/u6AuxMlMeJYkWeoq2SIVDK7VOj/l/op46UpVnmPiJdZHHuFboHUpgXHqDT4Mk8XqYmBTke7GyapCdpDLWvMWNkAGqr04T9T9Z/+1bt0phwCi1XbyghUjKecFAPjw8bXSEGMYXA2t7mT70ulJ21yL6gwBEtS4xtXviDYU8IdIrZemvOu74SZe9BISf2Fh8GiY3fROWx2qx8h06srqngsO/5dSK+i5cwdnuOem8O4b+re+Ca0tGbqTxf0vuIpHKhPhj3hK+PkOXAJMR6gVvkfTCFme8goovaZ5uj2GQzgdL/LRbVFeSO3fI3APL5sVeo9E/KW62jvdZ88LPAmNn4Y3UAvR0E6usNMnRhzHTucVgOuobjIAs+XELMxqDYKfhJ1Qsp4NGo+p4P3GgInNm2FeiRw1/xrRXWD/Yl1VudfKaRC5vX7iaWdG8nR0nEePFLiqixEogqR57jrtymmUqCG4oSVHXNedYtekDPHRVObH11bjXkyhbi1SfoMz9l3wRt9Yv+8ZsqQXgiFgYao9o="
    script:
    - sonar-scanner
  - stage: deploy to production
    script: npm run build
    deploy:
      provider: heroku
      cleanup: true
      api_key: "$HEROKU_API_KEY"
      strategy: git
      app: reactjs-ci
      on:
        branch: master
notifications:
  slack: ingenieriasof-97b7969:leLR2neDDHJhQqfmGqu8D1nF
