language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: code inspection
    addons:
      sonarcloud:
        organization: maurorojascabj
        token:
          secure: "HmUpMxFduYWFV1zwkouIO+VtcQ7ZwfVYhbs7ZJoWb3091xZOd3ex6a31dadsQ9um0Oy4VepoUD/TeZUVgRDlBiH7ac5HujrSjNBopWzEs/O2gWtz4dt2fbbJR7I/nshIYuknUbzRKB3T3oq3QYaZW0tvFW9VsTuuBT5xwykNvYdkQNv8OUfD+f5J2C+I47+osoUzlfeNfkcN+NvY0oQzM3pnxba0zIDn6w4HqFE6r5omEeflFgMnkwYjEv/Fpu2TORyiYaR300Ps8zXk9NPUb49l1Lcs7AX9Ju2j6RkHQCipFcjdsHojke7Hkaf1mVy+d/c5MBVvt1b0LSgBzogGeikPKUi+j0v1LurAYc2fqug3JlzSuDXUQ6IHSrupEc3TK1mw6/28Yzem/ZOy99KgcWHKCZvmWwWuq7P4WGVK+SF5/YQypPyH2CoCgec6gLqTsFp3B9yWVO7nCvQ+yPPDnGAxRyYv7DiwTtJZrnFLoGNW+8CT9cq6vzl+LZELNzAthCYwLuDuHZj5ACHdC1wmune4lf4DMvEKctpRx4Z3Okd07USNzB24HXp67r18pZFCkDc+5bvGKeBbjT2z3DGJyWdCGnArRutvD0a4gCSf7kDirsVDQ3Dr2S7kOG/Fo/rVN/o9bAi8jdDaDTMjU5ClEmeIB2y2hoQgj8ZhiUkcQL4="
    script:
    - sonar-scanner
  - stage: deploy to production
    script: npm run build
    deploy:
      provider: heroku
      cleanup: true
      api_key: "$HEROKU_API_KEY"
      strategy: git
      app: reactjs-ci
      on:
        branch: master
# notifications:
#   slack: ingenieriasof-97b7969:leLR2neDDHJhQqfmGqu8D1nF
